library(here)
library(ggplot2)
library(TMExplorer)
library(Seurat)
here::i_am("code/PCA_plot_fig1.R")
res = queryTME(geo_accession = "GSE131907")
res.seurat=as.Seurat(res[[1]], data = NULL)
res.seurat <- NormalizeData(res.seurat)
res.seurat <- FindVariableFeatures(res.seurat)
res.seurat <- ScaleData(res.seurat)
res.seurat <- RunPCA(res.seurat)
dp <- DimPlot(res.seurat, reduction = "pca") + NoLegend()
ggsave(here("figures", "Figure1.png"), plot = dp)